import { describe, test, expect } from "@jest/globals";
import { GraphData, getTreeData } from "./get-tree-data.js";
import { CommandDoc } from "../interface.js";

describe("getTreeData", () => {
  test.each([
    [
      {
        topic_vertices: [
          {
            _object_id: "UI_TEST_NODE@EASYOPS",
            creator: "easyops",
            ctime: "2023-08-24 18:04:19",
            deleteAuthorizers: [],
            instanceId: "603a85a03c2c6",
            label: "demo app",
            modifier: null,
            mtime: null,
            name: "suite",
            org: 8888,
            params: null,
            readAuthorizers: [],
            type: "suite",
            updateAuthorizers: [],
          },
        ],
        vertices: [
          {
            _object_id: "UI_TEST_NODE@EASYOPS",
            creator: "easyops",
            ctime: "2023-08-24 18:05:06",
            deleteAuthorizers: [],
            instanceId: "603a85ccfb595",
            label: "should work",
            modifier: null,
            mtime: null,
            name: "it",
            org: 8888,
            params: null,
            readAuthorizers: [],
            type: "block",
            updateAuthorizers: [],
          },
          {
            _object_id: "UI_TEST_NODE@EASYOPS",
            creator: "easyops",
            ctime: "2023-08-24 21:32:38",
            deleteAuthorizers: [],
            instanceId: "603ab42f8eae9",
            label: null,
            modifier: null,
            mtime: null,
            name: "beforeEach",
            org: 8888,
            params: null,
            readAuthorizers: [],
            type: "block",
            updateAuthorizers: [],
          },
          {
            _object_id: "UI_TEST_NODE@EASYOPS",
            creator: "easyops",
            ctime: "2023-08-24 18:31:29",
            deleteAuthorizers: [],
            instanceId: "603a8bb21c8e6",
            label: null,
            modifier: "easyops",
            mtime: "2023-08-24 19:44:38",
            name: "code",
            org: 8888,
            params: {
              content: "console.log(1323)",
            },
            readAuthorizers: [],
            type: "command",
            updateAuthorizers: [],
          },
          {
            _object_id: "UI_TEST_NODE@EASYOPS",
            creator: "easyops",
            ctime: "2023-08-24 20:55:24",
            deleteAuthorizers: [],
            instanceId: "603aabdd6d6cd",
            label: null,
            modifier: null,
            mtime: null,
            name: "get",
            org: 8888,
            params: null,
            readAuthorizers: [],
            type: "command",
            updateAuthorizers: [],
          },
          {
            _object_id: "UI_TEST_NODE@EASYOPS",
            creator: "easyops",
            ctime: "2023-08-24 21:33:33",
            deleteAuthorizers: [],
            instanceId: "603ab463e5d3e",
            label: null,
            modifier: null,
            mtime: null,
            name: "code",
            org: 8888,
            params: null,
            readAuthorizers: [],
            type: "command",
            updateAuthorizers: [],
          },
          {
            _object_id: "UI_TEST_NODE@EASYOPS",
            creator: "easyops",
            ctime: "2023-08-24 20:56:52",
            deleteAuthorizers: [],
            instanceId: "603aac31912bd",
            label: null,
            modifier: null,
            mtime: null,
            name: "type",
            org: 8888,
            params: null,
            readAuthorizers: [],
            type: "command",
            updateAuthorizers: [],
          },
          {
            _object_id: "UI_TEST_NODE@EASYOPS",
            creator: "easyops",
            ctime: "2023-08-24 20:57:25",
            deleteAuthorizers: [],
            instanceId: "603aac508c916",
            label: null,
            modifier: null,
            mtime: null,
            name: "click",
            org: 8888,
            params: null,
            readAuthorizers: [],
            type: "command",
            updateAuthorizers: [],
          },
        ],
        edges: [
          {
            relation_id:
              "UI_TEST_NODE@EASYOPS_parent_children_UI_TEST_NODE@EASYOPS",
            out: "603a85ccfb595",
            in: "603a85a03c2c6",
            out_name: "children",
            properties: null,
          },
          {
            relation_id:
              "UI_TEST_NODE@EASYOPS_parent_children_UI_TEST_NODE@EASYOPS",
            out: "603ab42f8eae9",
            in: "603a85a03c2c6",
            out_name: "children",
            properties: null,
          },
          {
            relation_id:
              "UI_TEST_NODE@EASYOPS_parent_children_UI_TEST_NODE@EASYOPS",
            out: "603a8bb21c8e6",
            in: "603a85ccfb595",
            out_name: "children",
            properties: null,
          },
          {
            relation_id:
              "UI_TEST_NODE@EASYOPS_parent_children_UI_TEST_NODE@EASYOPS",
            out: "603aabdd6d6cd",
            in: "603a85ccfb595",
            out_name: "children",
            properties: null,
          },
          {
            relation_id:
              "UI_TEST_NODE@EASYOPS_parent_children_UI_TEST_NODE@EASYOPS",
            out: "603ab463e5d3e",
            in: "603ab42f8eae9",
            out_name: "children",
            properties: null,
          },
          {
            relation_id:
              "UI_TEST_NODE@EASYOPS_parent_children_UI_TEST_NODE@EASYOPS",
            out: "603aac31912bd",
            in: "603aabdd6d6cd",
            out_name: "children",
            properties: null,
          },
          {
            relation_id:
              "UI_TEST_NODE@EASYOPS_parent_children_UI_TEST_NODE@EASYOPS",
            out: "603aac508c916",
            in: "603aabdd6d6cd",
            out_name: "children",
            properties: null,
          },
        ],
      },
      [
        {
          name: "code",
          category: "other",
          from: "custom",
          params: [
            {
              source: "string",
            },
          ],
        },
        {
          name: "get",
          description: "获取元素",
          category: "query",
          from: "cypress",
          chain: "parent",
        },
        {
          name: "type",
          description: "输入内容",
          category: "action",
          from: "cypress",
          chain: "child",
        },
        {
          name: "click",
          description: "点击",
          category: "action",
          from: "cypress",
          chain: "child",
        },
      ],
      {
        children: [
          {
            children: [
              {
                children: [],
                data: {
                  _object_id: "UI_TEST_NODE@EASYOPS",
                  creator: "easyops",
                  ctime: "2023-08-24 18:31:29",
                  deleteAuthorizers: [],
                  instanceId: "603a8bb21c8e6",
                  isChainChild: false,
                  label: null,
                  modifier: "easyops",
                  mtime: "2023-08-24 19:44:38",
                  name: "code",
                  org: 8888,
                  params: { content: "console.log(1323)" },
                  readAuthorizers: [],
                  type: "command",
                  updateAuthorizers: [],
                },
                icon: {
                  color: "var(--palette-green-6)",
                  icon: "control",
                  lib: "antd",
                  theme: "outlined",
                },
                key: "603a8bb21c8e6",
                name: "code",
              },
              {
                children: [
                  {
                    children: [],
                    data: {
                      _object_id: "UI_TEST_NODE@EASYOPS",
                      creator: "easyops",
                      ctime: "2023-08-24 20:56:52",
                      deleteAuthorizers: [],
                      instanceId: "603aac31912bd",
                      isChainChild: true,
                      label: null,
                      modifier: null,
                      mtime: null,
                      name: "type",
                      org: 8888,
                      params: null,
                      readAuthorizers: [],
                      type: "command",
                      updateAuthorizers: [],
                    },
                    icon: {
                      color: "var(--palette-red-6)",
                      icon: "tool",
                      lib: "antd",
                      theme: "outlined",
                    },
                    key: "603aac31912bd",
                    name: "type",
                  },
                  {
                    children: [],
                    data: {
                      _object_id: "UI_TEST_NODE@EASYOPS",
                      creator: "easyops",
                      ctime: "2023-08-24 20:57:25",
                      deleteAuthorizers: [],
                      instanceId: "603aac508c916",
                      isChainChild: true,
                      label: null,
                      modifier: null,
                      mtime: null,
                      name: "click",
                      org: 8888,
                      params: null,
                      readAuthorizers: [],
                      type: "command",
                      updateAuthorizers: [],
                    },
                    icon: {
                      color: "var(--palette-red-6)",
                      icon: "tool",
                      lib: "antd",
                      theme: "outlined",
                    },
                    key: "603aac508c916",
                    name: "click",
                  },
                ],
                data: {
                  _object_id: "UI_TEST_NODE@EASYOPS",
                  creator: "easyops",
                  ctime: "2023-08-24 20:55:24",
                  deleteAuthorizers: [],
                  instanceId: "603aabdd6d6cd",
                  isChainChild: false,
                  label: null,
                  modifier: null,
                  mtime: null,
                  name: "get",
                  org: 8888,
                  params: null,
                  readAuthorizers: [],
                  type: "command",
                  updateAuthorizers: [],
                },
                icon: {
                  color: "var(--palette-blue-6)",
                  icon: "search",
                  lib: "antd",
                  theme: "outlined",
                },
                key: "603aabdd6d6cd",
                name: "get",
              },
            ],
            data: {
              _object_id: "UI_TEST_NODE@EASYOPS",
              creator: "easyops",
              ctime: "2023-08-24 18:05:06",
              deleteAuthorizers: [],
              instanceId: "603a85ccfb595",
              isChainChild: false,
              label: "should work",
              modifier: null,
              mtime: null,
              name: "it",
              org: 8888,
              params: null,
              readAuthorizers: [],
              type: "block",
              updateAuthorizers: [],
            },
            icon: {
              color: "var(--palette-cyan-6)",
              icon: "block",
              lib: "antd",
              theme: "outlined",
            },
            key: "603a85ccfb595",
            name: "it: should work",
          },
          {
            children: [
              {
                children: [],
                data: {
                  _object_id: "UI_TEST_NODE@EASYOPS",
                  creator: "easyops",
                  ctime: "2023-08-24 21:33:33",
                  deleteAuthorizers: [],
                  instanceId: "603ab463e5d3e",
                  isChainChild: false,
                  label: null,
                  modifier: null,
                  mtime: null,
                  name: "code",
                  org: 8888,
                  params: null,
                  readAuthorizers: [],
                  type: "command",
                  updateAuthorizers: [],
                },
                icon: {
                  color: "var(--palette-green-6)",
                  icon: "control",
                  lib: "antd",
                  theme: "outlined",
                },
                key: "603ab463e5d3e",
                name: "code",
              },
            ],
            data: {
              _object_id: "UI_TEST_NODE@EASYOPS",
              creator: "easyops",
              ctime: "2023-08-24 21:32:38",
              deleteAuthorizers: [],
              instanceId: "603ab42f8eae9",
              isChainChild: false,
              label: null,
              modifier: null,
              mtime: null,
              name: "beforeEach",
              org: 8888,
              params: null,
              readAuthorizers: [],
              type: "block",
              updateAuthorizers: [],
            },
            icon: {
              color: "var(--palette-cyan-6)",
              icon: "block",
              lib: "antd",
              theme: "outlined",
            },
            key: "603ab42f8eae9",
            name: "beforeEach",
          },
        ],
        data: {
          _object_id: "UI_TEST_NODE@EASYOPS",
          creator: "easyops",
          ctime: "2023-08-24 18:04:19",
          deleteAuthorizers: [],
          instanceId: "603a85a03c2c6",
          label: "demo app",
          modifier: null,
          mtime: null,
          name: "suite",
          org: 8888,
          params: null,
          readAuthorizers: [],
          type: "suite",
          updateAuthorizers: [],
        },
        icon: {
          color: "var(--palette-purple-6)",
          icon: "file",
          lib: "antd",
          theme: "outlined",
        },
        key: "603a85a03c2c6",
        name: "suite",
      },
    ],
  ])("should work", (GraphData, commandDocs, result) => {
    expect(
      getTreeData(GraphData as GraphData, commandDocs as CommandDoc[])
    ).toEqual(result);
  });
});
