export const mockData = [
  {
      "__label": [
          "B-63331"
      ],
      "_object_id": "STORYBOARD_ROUTE",
      "_object_version": 354,
      "_pre_ts": 1664352203,
      "_schema_groups": [],
      "_tf_lineage": null,
      "_tfstate": null,
      "_ts": 1671524906,
      "_version": 23,
      "alias": "page3",
      "analyticsData": null,
      "appId": "sailor-test-route-clone-1",
      "context": [
          {
              "name": "test2",
              "path": "root",
              "value": "test2"
          },
          {
              "name": "a",
              "path": ""
          }
      ],
      "creator": "easyops",
      "ctime": "2022-08-16 11:49:05",
      "defineResolves": null,
      "deleteAuthorizers": [],
      "documentId": null,
      "exact": true,
      "graphInfo": null,
      "hybrid": false,
      "id": "B-63331",
      "if": null,
      "instanceId": "5e653a1459032",
      "lock": false,
      "menu": "{\n  \"breadcrumb\": {\n    \"items\": [\n      {\n        \"text\": \"route-test\"\n      }\n    ]\n  }\n}",
      "modifier": "easyops",
      "mountPoint": null,
      "mtime": "2022-12-20 16:28:26",
      "org": 8888,
      "path": "${APP.homepage}/route-1/:instanceId/page3/:id",
      "permissionsPreCheck": null,
      "previewSettings": [
          {
              "active": false,
              "url": "/next/sailor-test-route-clone-1/route-1/instanceId1/page3/id1\n"
          },
          {
              "active": false,
              "url": "/sailor-test-route-clone-1/route-1/instanceId1/page3/id2\n"
          },
          {
              "active": true,
              "url": "${APP.homepage}/route-1/instanceId1/page3/id3\n"
          }
      ],
      "providers": null,
      "providers_bak": null,
      "public": false,
      "readAuthorizers": [],
      "redirect": "\"\"",
      "screenshot": null,
      "segues": null,
      "sort": 1,
      "type": "bricks",
      "updateAuthorizers": [],
      "children": [
          {
              "__label": [
                  "B-74021"
              ],
              "_object_id": "STORYBOARD_BRICK",
              "_object_version": 170,
              "_pre_ts": 1680170609,
              "_schema_groups": [],
              "_tf_lineage": null,
              "_tfstate": null,
              "_ts": 1680170638,
              "_version": 4,
              "alias": null,
              "appId": null,
              "bg": false,
              "brick": "container-brick.tabs-container",
              "context": null,
              "creator": "easyops",
              "ctime": "2023-03-30 16:48:55",
              "deleteAuthorizers": [],
              "events": "{\n  \"tab.select\": [\n    {\n      \"action\": \"console.log\"\n    },\n    {\n      \"action\": \"message.success\",\n      \"args\": [\n        \"改变tab\"\n      ]\n    }\n  ]\n}",
              "exports": null,
              "id": "B-74021",
              "if": null,
              "injectDeep": true,
              "instanceId": "5f81a29b25a4b",
              "lifeCycle": null,
              "modifier": "easyops",
              "mountPoint": "bricks",
              "mtime": "2023-03-30 18:03:58",
              "org": 8888,
              "params": null,
              "permissionsPreCheck": null,
              "portal": false,
              "properties": "{\n  \"activeTabIndex\": 0,\n  \"size\": \"small\",\n  \"slotType\": \"bricks\",\n  \"tabList\": [\n    {\n      \"key\": \"Tab1\",\n      \"text\": \"Tab1\"\n    },\n    {\n      \"disabled\": true,\n      \"key\": \"Tab2\",\n      \"text\": \"Tab2\"\n    },\n    {\n      \"badgeConf\": {\n        \"color\": \"red\",\n        \"count\": 100,\n        \"dot\": true\n      },\n      \"key\": \"Tab3\",\n      \"text\": \"Tab3\"\n    }\n  ],\n  \"dataset\": {\n    \"testid\": \"tabs-container-normal\"\n  }\n}",
              "readAuthorizers": [],
              "ref": null,
              "sort": 0,
              "transform": null,
              "transformFrom": null,
              "type": "brick",
              "updateAuthorizers": [],
              "children": [
                  {
                      "__label": [
                          "B-74022"
                      ],
                      "_object_id": "STORYBOARD_BRICK",
                      "_object_version": 170,
                      "_pre_ts": 1680247149,
                      "_schema_groups": [],
                      "_tf_lineage": null,
                      "_tfstate": null,
                      "_ts": 1680247161,
                      "_version": 3,
                      "alias": null,
                      "appId": null,
                      "bg": false,
                      "brick": "div",
                      "context": null,
                      "creator": "easyops",
                      "ctime": "2023-03-30 16:48:56",
                      "deleteAuthorizers": [],
                      "events": null,
                      "exports": null,
                      "id": "B-74022",
                      "if": null,
                      "injectDeep": true,
                      "instanceId": "5f81a29b5b60f",
                      "lifeCycle": "{\n  \"useResolves\": [\n    {\n      \"useProvider\": \"providers-of-cmdb.instance-api-post-search-v3\",\n      \"args\": [\n        \"DEVELOPMENT_ENVS\",\n        {\n          \"fields\": [\n            \"openApiIP\",\n            \"openApiPort\",\n            \"accessKey\",\n            \"secretKey\",\n            \"protocol\",\n            \"previewIP\"\n          ],\n          \"page\": 1,\n          \"pageSize\": 3000\n        }\n      ],\n      \"transform\": {\n        \"textContent\": \"<% DATA.list[0].openApiIP %>\"\n      }\n    }\n  ]\n}",
                      "modifier": "easyops",
                      "mountPoint": "content",
                      "mtime": "2023-03-31 15:19:21",
                      "org": 8888,
                      "params": null,
                      "permissionsPreCheck": null,
                      "portal": false,
                      "properties": "{\n  \"textContent\": \"small Panel 1\"\n}",
                      "readAuthorizers": [],
                      "ref": null,
                      "sort": 0,
                      "transform": null,
                      "transformFrom": null,
                      "type": "brick",
                      "updateAuthorizers": [],
                      "children": [
                          {
                              "__label": [
                                  "B-74040"
                              ],
                              "_object_id": "STORYBOARD_BRICK",
                              "_object_version": 170,
                              "_pre_ts": 1680231418,
                              "_schema_groups": [],
                              "_tf_lineage": null,
                              "_tfstate": null,
                              "_ts": 1680232303,
                              "_version": 6,
                              "alias": null,
                              "appId": null,
                              "bg": false,
                              "brick": "forms.general-select",
                              "context": null,
                              "creator": "easyops",
                              "ctime": "2023-03-31 10:54:45",
                              "deleteAuthorizers": [],
                              "events": "{\n  \"general.select.change\": {\n    \"action\": \"console.log\",\n    \"args\": [\n      \"gender\",\n      \"<% EVENT.detail %>\"\n    ]\n  },\n  \"general.select.change.v2\": [\n    {\n      \"action\": \"console.log\",\n      \"args\": [\n        \"gender\",\n        \"<% EVENT.detail %>\"\n      ]\n    }\n  ]\n}",
                              "exports": null,
                              "id": "B-74040",
                              "if": null,
                              "injectDeep": true,
                              "instanceId": "5f82954ebae5b",
                              "lifeCycle": null,
                              "modifier": "defaultUser",
                              "mountPoint": "content",
                              "mtime": "2023-03-31 11:11:43",
                              "org": 8888,
                              "params": null,
                              "permissionsPreCheck": null,
                              "portal": false,
                              "properties": "{\n  \"emptyOption\": {\n    \"label\": \"不分性别\",\n    \"value\": \"\"\n  },\n  \"inputBoxStyle\": {\n    \"width\": 120\n  },\n  \"label\": \"性别\",\n  \"name\": \"gender\",\n  \"options\": [\n    {\n      \"label\": \"男\",\n      \"value\": \"male\"\n    },\n    {\n      \"label\": \"女\",\n      \"value\": \"female\"\n    }\n  ],\n  \"mode\": \"multiple\",\n  \"placeholder\": \"请选择性别\",\n  \"value\": \"female\",\n  \"dataset\": {\n    \"testid\": \"basic-usage-demo\"\n  }\n}",
                              "readAuthorizers": [],
                              "ref": null,
                              "sort": 0,
                              "transform": null,
                              "transformFrom": null,
                              "type": "brick",
                              "updateAuthorizers": []
                          },
                          {
                              "__label": [
                                  "B-74041"
                              ],
                              "_object_id": "STORYBOARD_BRICK",
                              "_object_version": 170,
                              "_pre_ts": 1680232669,
                              "_schema_groups": [],
                              "_tf_lineage": null,
                              "_tfstate": null,
                              "_ts": 1680233520,
                              "_version": 3,
                              "alias": null,
                              "appId": "sailor-test-route-clone-1",
                              "bg": false,
                              "brick": "presentational-bricks.brick-tag",
                              "context": null,
                              "creator": "easyops",
                              "ctime": "2023-03-31 11:11:43",
                              "deleteAuthorizers": [],
                              "events": "{\n  \"checked.update\": {\n    \"action\": \"console.log\",\n    \"args\": [\n      \"checked.update\",\n      \"<% EVENT.detail[0] %>\"\n    ]\n  },\n  \"checked.update.v2\": {\n    \"action\": \"console.log\",\n    \"args\": [\n      \"checked.update.v2\",\n      \"<% EVENT.detail %>\"\n    ]\n  },\n  \"tag.click\": {\n    \"action\": \"console.log\",\n    \"args\": [\n      \"tag.click\",\n      \"${EVENT.detail}\"\n    ]\n  },\n  \"tag.close\": {\n    \"action\": \"console.log\",\n    \"args\": [\n      \"tag.close\",\n      \"${EVENT.detail.current}\",\n      \"<% EVENT.detail.tagList %>\"\n    ]\n  }\n}",
                              "exports": null,
                              "id": "B-74041",
                              "if": null,
                              "injectDeep": true,
                              "instanceId": "5f8299196d0ab",
                              "lifeCycle": null,
                              "modifier": "easyops",
                              "mountPoint": "content",
                              "mtime": "2023-03-31 11:32:00",
                              "org": 8888,
                              "params": null,
                              "permissionsPreCheck": null,
                              "portal": false,
                              "properties": "{\n  \"closable\": true,\n  \"showCard\": false,\n  \"tagList\": [\n    {\n      \"disabled\": true,\n      \"key\": \"p1\",\n      \"label\": \"紧急变更\"\n    },\n    {\n      \"disabled\": true,\n      \"key\": \"p2\",\n      \"label\": \"计划变更\"\n    },\n    {\n      \"key\": \"p3\",\n      \"label\": \"发布流程\"\n    },\n    {\n      \"key\": \"p4\",\n      \"label\": \"发布流程\"\n    },\n    {\n      \"key\": \"p5\",\n      \"label\": \"发布计划\"\n    },\n    {\n      \"key\": \"p6\",\n      \"label\": \"测试计划\"\n    }\n  ],\n  \"dataset\": {\n    \"testid\": \"tag\"\n  }\n}",
                              "readAuthorizers": [],
                              "ref": null,
                              "sort": 1,
                              "transform": null,
                              "transformFrom": null,
                              "type": "brick",
                              "updateAuthorizers": []
                          }
                      ]
                  },
                  {
                      "__label": [
                          "B-74023"
                      ],
                      "_object_id": "STORYBOARD_BRICK",
                      "_object_version": 170,
                      "_pre_ts": null,
                      "_schema_groups": [],
                      "_tf_lineage": null,
                      "_tfstate": null,
                      "_ts": 1680166136,
                      "_version": 1,
                      "alias": null,
                      "appId": null,
                      "bg": null,
                      "brick": "div",
                      "context": null,
                      "creator": "easyops",
                      "ctime": "2023-03-30 16:48:56",
                      "deleteAuthorizers": [],
                      "events": null,
                      "exports": null,
                      "id": "B-74023",
                      "if": null,
                      "injectDeep": true,
                      "instanceId": "5f81a29b81a2b",
                      "lifeCycle": null,
                      "modifier": null,
                      "mountPoint": "content",
                      "mtime": null,
                      "org": 8888,
                      "params": null,
                      "permissionsPreCheck": null,
                      "portal": false,
                      "properties": "{\"textContent\":\"small Panel 2\"}",
                      "readAuthorizers": [],
                      "ref": null,
                      "sort": 1,
                      "transform": null,
                      "transformFrom": null,
                      "type": "brick",
                      "updateAuthorizers": []
                  },
                  {
                      "__label": [
                          "B-74024"
                      ],
                      "_object_id": "STORYBOARD_BRICK",
                      "_object_version": 170,
                      "_pre_ts": 1680166136,
                      "_schema_groups": [],
                      "_tf_lineage": null,
                      "_tfstate": null,
                      "_ts": 1680231285,
                      "_version": 2,
                      "alias": null,
                      "appId": null,
                      "bg": null,
                      "brick": "div",
                      "context": null,
                      "creator": "easyops",
                      "ctime": "2023-03-30 16:48:56",
                      "deleteAuthorizers": [],
                      "events": null,
                      "exports": null,
                      "id": "B-74024",
                      "if": null,
                      "injectDeep": true,
                      "instanceId": "5f81a29ba9427",
                      "lifeCycle": null,
                      "modifier": "defaultUser",
                      "mountPoint": "content",
                      "mtime": "2023-03-31 10:54:45",
                      "org": 8888,
                      "params": null,
                      "permissionsPreCheck": null,
                      "portal": false,
                      "properties": "{\"textContent\":\"small Panel 3\"}",
                      "readAuthorizers": [],
                      "ref": null,
                      "sort": 3,
                      "transform": null,
                      "transformFrom": null,
                      "type": "brick",
                      "updateAuthorizers": []
                  }
              ]
          }
      ]
  }
]
